name: chris / brookins
description: Simple solutions
meta_description: "built on jekyll"

markdown: redcarpet
encoding: UTF-8
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://cbrookins.github.io'
author:         'Chris'
