name: chris / brookins
description: 
meta_description: "built on jekyll"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://cbrookins.github.io'
author:         'Chris'
